version: '2.1'
services:
    sut:
        build: .
        build:
            context: .
            dockerfile: Dockerfile.test
        links:
            - api

    api:
        container_name: api
        depends_on:
            db:
                condition: service_healthy
        volumes:
        - .:/code

    db:
        container_name: db
        image: mysql
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: "camspass"
            MYSQL_USER: "camsuser"
            MYSQL_PASSWORD: "camspass"
            MYSQL_DATABASE: "CIMD"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
