version: '2.1'
services:

    api:
        build: .
        image: centos:7
        build:
            dockerfile: Dockerfile-test
        container_name: api
        command: "echo 'WTF2'"
        depends_on:
            db:
                condition: service_healthy
        volumes:
        - .:/code

    db:
        container_name: db
        image: mysql
        hostname: db
        ports:
            - "3306"
        command: "echo 'WTF'"
        environment:
            MYSQL_ROOT_PASSWORD: "camspass"
            MYSQL_USER: "camsuser"
            MYSQL_PASSWORD: "camspass"
            MYSQL_DATABASE: "CIMD"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
