web:
  build: .
  command: bash -c "python manage.py makemigrations --merge && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=camspass
    - MYSQL_USER=camsuser
    - MYSQL_PASSWORD=camspass
    - MYSQL_DATABASE=CIMD


 # command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]