# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0002_auto_20170317_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
    ]
