# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='model_pic',
            field=models.ImageField(default='media/no-img.jpg', upload_to='media/'),
        ),
    ]
