# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20170317_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='model_pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
