# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20170322_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='model_pic',
            field=models.ImageField(max_length=50000, upload_to='onboarding/'),
        ),
    ]
