# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_auto_20170322_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('model_pic', models.ImageField(max_length=500, upload_to='onboarding/')),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
