# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_auto_20170327_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesnapshot',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to='/home/gniorg/Documents/CIMD/website/onboarding/media/onboarding/'),
        ),
    ]
