# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_auto_20170711_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesnapshot',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to='/code/media/onboarding/'),
        ),
    ]
