# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 14:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_usercontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='birthdate',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='expiracydate',
            new_name='doe',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='usercontact',
            name='sex',
            field=models.CharField(blank=True, max_length=1, validators=[django.core.validators.RegexValidator(message='Must be 8 numbers followed by 1 capital letter', regex='^[A-Z]{1}$')], verbose_name='sex'),
        ),
    ]
